version: '3.9'
services:
    squat:
        image: shanduur/squat:latest
        restart: on-failure
        ports: 
            - '8080:8080'
        volumes:
            - data:/etc/squat/data
            - config:/etc/squat/config
    postgres:
        image: postgres
        restart: on-failure
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: example
volumes: 
    data:
    config:
