on:
  push:
    tags:
      - '*'
name: Build Docker image
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: get previous tag
        id: previous-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: v0.0.1 # Optional fallback tag to use when no tag can be found
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: login to docker hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          cd docker && docker buildx build \
            --push \
            --tag shanduur/squat:latest \
            --no-cache \
            --tag shanduur/squat:${{ steps.previous-tag.outputs.tag }} \
            --platform linux/amd64,linux/arm64 \
            .
  # update-readme:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout code
  #       uses: actions/checkout@v2
  #     - name: update description
  #       uses: peter-evans/dockerhub-description@v2
  #       env:
  #         DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  #         DOCKERHUB_REPOSITORY: peterevans/dockerhub-description
