on:
  pull_request:
    branches:
      - main
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install -y \
          unixodbc \
          unixodbc-dev
    - name: Test
      env:
        TEST_NO_DB: true
      run: |
        go test -coverprofile coverage.txt -covermode atomic ./...
    - name: Upload report
      env:
        CODECOV_TOKEN: "{{ secrets.CODECOV_TOKEN }}"
      run: |
        bash <(curl -s https://codecov.io/bash)
